import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

import { motion } from "framer-motion";

import { GraphQLClient } from "graphql-request";
import { gql } from "graphql-request";

const hygraph = new GraphQLClient(
  "https://api-eu-central-1-shared-euc1-02.hygraph.com/v2/cl9s32g1q2oun01td822bh5s6/master"
);

const QUERY = gql`
  {
    projects {
      id
      title
      slug
      tags
      mainImage {
        url
        width
        height
      }
    }
  }
`;

export async function getStaticProps() {
  const { projects } = await hygraph.request(QUERY);

  return {
    props: {
      projects,
    },
  };
}

export default function Home({ projects }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          {projects.map(({ id, title, mainImage, slug, tags }) => (
            <div key={slug}>
              <div>
                <Link href={`/projects/${slug}`}>
                  <motion.h1 layoutId="title">{title}</motion.h1>
                </Link>
                <div>
                  <motion.img
                    layoutId="image"
                    src={mainImage.url}
                    alt={title}
                    width={500}
                  />
                </div>
              </div>
            </div>
          ))}
        </div>

        <h1>Avidu</h1>
        <h2 id="about">About Me</h2>
        <h2 id="work">Work</h2>
        <h2 id="contact">Contact</h2>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
